server:
  port: 8090
  servlet:
    context-path: /api/v1

spring:
  application:
    name: mailer-back
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL}
    password: ${PWD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true